"""reset_token

Revision ID: 346ac7f574b2
Revises: 1e7291275485
Create Date: 2026-02-04 20:18:45.960497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '346ac7f574b2'
down_revision: Union[str, Sequence[str], None] = '1e7291275485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('expiry_token_time', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('Customers', sa.Column('reset_password_token', sa.UUID(), nullable=True))
    op.add_column('Customers', sa.Column('expiry_reset_token_time', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Customers', 'expiry_reset_token_time')
    op.drop_column('Customers', 'reset_password_token')
    op.drop_column('Customers', 'expiry_token_time')
    # ### end Alembic commands ###
