"""rbac

Revision ID: 7d587bbe48ba
Revises: 9714291c3c08
Create Date: 2025-12-22 18:28:03.092769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d587bbe48ba'
down_revision: Union[str, Sequence[str], None] = '9714291c3c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('role', sa.VARCHAR(), server_default='User', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Customers', 'role')
    # ### end Alembic commands ###
