"""empty message

Revision ID: cdd89869c391
Revises: 7d587bbe48ba
Create Date: 2026-01-29 02:08:30.598854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cdd89869c391'
down_revision: Union[str, Sequence[str], None] = '7d587bbe48ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Customers', 'token')
    # ### end Alembic commands ###
