"""empty message

Revision ID: e36cabc774de
Revises: cdd89869c391
Create Date: 2026-01-29 19:15:21.662155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36cabc774de'
down_revision: Union[str, Sequence[str], None] = 'cdd89869c391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Customers', 'token',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Customers', 'token',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
