"""adding_new_admin

Revision ID: e3d2b7343f9a
Revises: 4eeb4b6ef89c
Create Date: 2026-02-04 20:43:20.313839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e3d2b7343f9a'
down_revision: Union[str, Sequence[str], None] = '4eeb4b6ef89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
