"""add item table and refactor sales table

Revision ID: 95a91e881cb8
Revises: 
Create Date: 2026-09-15 14:13:54.160120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a91e881cb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sales', sa.Column('total_price', sa.Float(), nullable=False))
    op.drop_constraint(op.f('Sales_uid_fkey'), 'Sales', type_='foreignkey')
    op.drop_column('Sales', 'uid')
    op.drop_column('Sales', 'price')
    op.drop_column('Sales', 'amount_bought')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sales', sa.Column('amount_bought', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Sales', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('Sales', sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('Sales_uid_fkey'), 'Sales', 'CologneInfo', ['uid'], ['uid'])
    op.drop_column('Sales', 'total_price')
    # ### end Alembic commands ###
