"""add item table

Revision ID: eddc834aac12
Revises: 95a91e881cb8
Create Date: 2026-09-15 14:16:07.930569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eddc834aac12'
down_revision: Union[str, Sequence[str], None] = '95a91e881cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('delivery_date', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['sales_id'], ['Sales.sales_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['CologneInfo.uid'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Items')
    # ### end Alembic commands ###
