"""create_all_tables

Revision ID: f178e85dd341
Revises: 
Create Date: 2026-08-07 16:25:36.608647

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f178e85dd341'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CologneInfo',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_CologneInfo_brand'), 'CologneInfo', ['brand'], unique=False)
    op.create_index(op.f('ix_CologneInfo_image_url'), 'CologneInfo', ['image_url'], unique=False)
    op.create_index(op.f('ix_CologneInfo_name'), 'CologneInfo', ['name'], unique=False)
    op.create_index(op.f('ix_CologneInfo_type'), 'CologneInfo', ['type'], unique=False)
    op.create_table('Customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sa.UUID(), nullable=True),
    sa.Column('expiry_token_time', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('role', sa.VARCHAR(), server_default='User', nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('sign_up_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_update_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('reset_password_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expiry_reset_token_time', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_Customers_email'), 'Customers', ['email'], unique=True)
    op.create_index(op.f('ix_Customers_hash_password'), 'Customers', ['hash_password'], unique=False)
    op.create_table('Sales',
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('amount_bought', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sale_date', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.customer_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['CologneInfo.uid'], ),
    sa.PrimaryKeyConstraint('sales_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sales')
    op.drop_index(op.f('ix_Customers_hash_password'), table_name='Customers')
    op.drop_index(op.f('ix_Customers_email'), table_name='Customers')
    op.drop_table('Customers')
    op.drop_index(op.f('ix_CologneInfo_type'), table_name='CologneInfo')
    op.drop_index(op.f('ix_CologneInfo_name'), table_name='CologneInfo')
    op.drop_index(op.f('ix_CologneInfo_image_url'), table_name='CologneInfo')
    op.drop_index(op.f('ix_CologneInfo_brand'), table_name='CologneInfo')
    op.drop_table('CologneInfo')
    # ### end Alembic commands ###
